/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"
#include <stdio.h>

int *
somavet_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Requisicao para adicao de %d numeros\n", argp->n);
   result =0;
   printf("> somando %d", argp->x[0]);
   result += argp->x[0];
   for(int i=1; i<argp->n; i++){
      printf(" + %d", argp->x[i]);
      result += argp->x[i];
   }
   printf("\nPronto\n");

	return &result;
}
