/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"
#include <stdio.h>
#include <stdlib.h>

void
main_100(char *host, operandos *somavet_100_arg)
{
	CLIENT *clnt;
	int  *result_1;

	// printf("debug client\n");
	// for(int i=0; i<somavet_100_arg->n; i++){
	// 	printf("recebi %d ", somavet_100_arg->x[i]);
	// }
	// printf("\n");

#ifndef	DEBUG
	clnt = clnt_create (host, MAIN, UM, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = somavet_100(somavet_100_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Resultado de %d", somavet_100_arg->x[0]);
	for(int i=1; i<somavet_100_arg->n; i++){
		printf(" + %d", somavet_100_arg->x[i]);
	}
	printf(" é = %d\n", *result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host num1 num2 ...\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	operandos  somavet_100_arg;

	somavet_100_arg.n = argc - 2;
	somavet_100_arg.x = (int *) malloc(somavet_100_arg.n * sizeof(int));

	for(int i=2; i<argc; i++){
		// printf("atoi %d\n", atoi(argv[i]));
      somavet_100_arg.x[i-2] = atoi(argv[i]);
   }

	main_100 (host, &somavet_100_arg);
exit (0);
}
