/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>

int * calcula_1_svc(argp, rqstp)
	operacao *argp;
	struct svc_req *rqstp;
{

	static int  result;

	switch (argp->opr){
      case '+':
         result = (argp->op1 + argp->op2);
			break;

      case '-':
         result = (argp->op1 - argp->op2);
			break;

      case '/':
         result = (argp->op1 / argp->op2);
			break;

      case '@': // foi necessario utilizar esse simbolo porque, ao que parece, o "*" e interpretado pelo shell ao inves de ser entendido como parametro
         result = (argp->op1 * argp->op2);
			break;

      default:
         printf("\nERRO: operação não suportada!\n");
         printf("Operações suportadas:\n\t-> +\n\t-> -\n\t-> @ (multiplicação)\n\t-> /\n");
         exit(1);
   }

	return(&result);
}
