/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdlib.h>
#include <stdio.h>

void
calculadora_1(host, op1, opr, op2)
char *host;
int op1;
char opr;
int op2;
{
	CLIENT *clnt;
	int  *result_1;
	operacao  calcula_1_arg;

	calcula_1_arg.op1 = op1;
	calcula_1_arg.op2 = op2;
	calcula_1_arg.opr = opr;

	clnt = clnt_create(host, CALCULADORA, LAB01, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = calcula_1(&calcula_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}

	printf("\n--> Calculadora: o resultado é %d\n", *result_1);

	clnt_destroy( clnt );
}


int main(argc, argv)
int argc;
char *argv[];
{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	int op1 = atoi(argv[2]);
   char opr = *argv[3];
   int op2 = atoi(argv[4]);

	calculadora_1( host, op1, opr, op2 );

	return 0;
}
