/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct operacao {
	int op1;
	char opr;
	int op2;
};
typedef struct operacao operacao;
#ifdef __cplusplus
extern "C" bool_t xdr_operacao(XDR *, operacao*);
#elif __STDC__
extern  bool_t xdr_operacao(XDR *, operacao*);
#else /* Old Style C */
bool_t xdr_operacao();
#endif /* Old Style C */


#define CALCULADORA ((rpc_uint)10)
#define LAB01 ((rpc_uint)1)

#ifdef __cplusplus
#define calcula ((rpc_uint)1)
extern "C" int * calcula_1(operacao *, CLIENT *);
extern "C" int * calcula_1_svc(operacao *, struct svc_req *);

#elif __STDC__
#define calcula ((rpc_uint)1)
extern  int * calcula_1(operacao *, CLIENT *);
extern  int * calcula_1_svc(operacao *, struct svc_req *);

#else /* Old Style C */
#define calcula ((rpc_uint)1)
extern  int * calcula_1();
extern  int * calcula_1_svc();
#endif /* Old Style C */

#endif /* !_CALCULADORA_H_RPCGEN */
