/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_operacao(xdrs, objp)
	XDR *xdrs;
	operacao *objp;
{

	if (!xdr_int(xdrs, &objp->op1))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->opr))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->op2))
		return (FALSE);
	return (TRUE);
}
