/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

int *
add_100(argp, rqstp)
	operandos *argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
sub_100(argp, rqstp)
	operandos *argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
